version: '3.8'
services:
  app:
    container_name: app-crypto-dash
    build:
      context: ./client/.
      target: develop-stage
    command: 'npm run dev'
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"


